<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MonolithModularNET.User.Core\MonolithModularNET.User.Core.csproj" />
      <ProjectReference Include="..\MonolithModularNET.User\MonolithModularNET.User.csproj" />
    </ItemGroup>

</Project>
