FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["WebApi/WebApi.csproj", "WebApi/"]
COPY ["Modules/MonolithModularNET.Auth/MonolithModularNET.Auth.csproj", "Modules/MonolithModularNET.Auth/"]
COPY ["Modules/MonolithModularNET.Auth.Core/MonolithModularNET.Auth.Core.csproj", "Modules/MonolithModularNET.Auth.Core/"]
COPY ["Modules/MonolithModularNET.Extensions.Shared/MonolithModularNET.Extensions.Shared.csproj", "Modules/MonolithModularNET.Extensions.Shared/"]
COPY ["Modules/MonolithModularNET.Extensions.Abstractions/MonolithModularNET.Extensions.Abstractions.csproj", "Modules/MonolithModularNET.Extensions.Abstractions/"]
COPY ["Modules/MonolithModularNET.Master.Infrastructure/MonolithModularNET.Master.Infrastructure.csproj", "Modules/MonolithModularNET.Master.Infrastructure/"]
COPY ["Modules/MonolithModularNET.Master/MonolithModularNET.Master.csproj", "Modules/MonolithModularNET.Master/"]
COPY ["Modules/MonolithModularNET.Master.Core/MonolithModularNET.Master.Core.csproj", "Modules/MonolithModularNET.Master.Core/"]
COPY ["Modules/MonolithModularNET.Extensions.Core/MonolithModularNET.Extensions.Core.csproj", "Modules/MonolithModularNET.Extensions.Core/"]
COPY ["Modules/MonolithModularNET.User.Infrastructure/MonolithModularNET.User.Infrastructure.csproj", "Modules/MonolithModularNET.User.Infrastructure/"]
COPY ["Modules/MonolithModularNET.User.Core/MonolithModularNET.User.Core.csproj", "Modules/MonolithModularNET.User.Core/"]
COPY ["Modules/MonolithModularNET.User/MonolithModularNET.User.csproj", "Modules/MonolithModularNET.User/"]
RUN dotnet restore "WebApi/WebApi.csproj"
COPY . .
WORKDIR "/src/WebApi"
RUN dotnet build "WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApi.dll"]
