version: '3.4'

services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    restart: unless-stopped
  
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    restart: unless-stopped
    volumes:
      - redisinsight:/data
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456@#}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres_network


volumes:
  postgres:
  pgadmin:
  redisinsight:

networks:
  postgres_network:
    driver: bridge